[package]
name = "meta-wshandler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }

log = "0.4"
fast_log = "1.3"

websocket = "0.26.0"
crossbeam-channel = "0.5"
backtrace = "0.3"