[workspace]
members = [
    "database",
    "repo",
<<<<<<< Updated upstream
    "protocol",
=======
<<<<<<< Updated upstream
=======
    "protocol",
    "node",
>>>>>>> Stashed changes
>>>>>>> Stashed changes
]